---

- name: tensorflow | Set variables
  set_fact:
    whl_url: "https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v1.0.0/tensorflow-1.0.0-cp27-none-linux_armv7l.whl"
    whl_path: "{{ soft_dir }}/tensorflow-1.0.0-cp27-none-linux_armv7l.whl"

- name: tensorflow | Download
  get_url:
    url: "{{ whl_url }}"
    dest: "{{ whl_path }}"

- name: tensorflow | Install
  pip:
    name: "{{ whl_path }}"